### ISSUE TITLE
session-timeout not working when the device is on sleep.

### ISSUE THREAD

**Issue by ashokraghu14** [LaeraFelipe/react-session-control#2]
@LaeraFelipe It's now working when the device is locked, but it's not working when the device is on sleep. Please check is there any fix for that too. Also when there's any background API call in-progress, the session shouldn't expire. Thanks in advance.

**Comment by ashokraghu14** [comment]
@LaeraFelipe Any update on this.

**Comment by LaeraFelipe** [comment]
@ashokraghu14  i'm sorry for answering so late. I made some changes to the component to always compare the last activity with the maximum downtime and log out if necessary. I also added a new "disabled" property to disable the checks made by the component. This way you can disable it when making an api call.
